# .golangci.yml

# Configuration file for golangci-lint to diagnose parsing issues.

version: "2"

run:
  # Set a timeout for the linter. 5m is a generous default.
  timeout: 5m
  
  # Don't lint files in the vendor directory.
  skip-dirs:
    - vendor/

linters-settings:
  # Configure depguard to allow necessary imports for our project.
  depguard:
    rules:
      Main:
        allow:
          - $gostd
          - github.com/bgreenwell/gitego
          - github.com/spf13/cobra
          - github.com/zalando/go-keyring
          - gopkg.in/yaml.v3
  # Increase the complexity tolerance slightly for now.
  cyclop:
    max-complexity: 15
  funlen:
    lines: 80 # Allow functions to be a bit longer, especially in tests.
    statements: 60
  gocognit:
    min-complexity: 40 # Increase the cognitive complexity limit.
  lll:
    line-length: 120
  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2

# Linters to enable. We start with a standard, essential set.
linters:
  default: fast
  enable:
    - wsl_v5
  disable:
    - gochecknoinits
    - depguard
    - testpackage
    - wsl

# How to report issues.
issues:
  # Don't use the default set of exclusions.
  exclude-use-default: false
  # Set the maximum number of issues of the same type to show.
  max-same-issues: 500
