# .golangci.yml
# A simplified configuration file for golangci-lint to diagnose parsing issues.
version: "2"
run:
  # Set a timeout for the linter. 5m is a generous default.
  timeout: 5m
  
  # Don't lint files in the vendor directory.
  skip-dirs:
    - vendor/

# Linters to enable. We start with a standard, essential set.
linters:
  default: fast


# How to report issues.
issues:
  # Don't use the default set of exclusions.
  exclude-use-default: false
  # Set the maximum number of issues of the same type to show.
  max-same-issues: 50
